# Generated by Django 6.0.1 on 2026-01-14 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recyclingtransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='recyclingtransaction',
            name='material_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('can', 'Can')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recyclingtransaction',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='recyclingtransaction',
            index=models.Index(fields=['user', 'material_type', '-timestamp'], name='main_recycl_user_id_090e4d_idx'),
        ),
    ]
